### ISSUE TITLE
Error when build with Webpack

### ISSUE THREAD

**Issue by hog-seruj** [GoogleChromeLabs/container-query-polyfill#13]
ERROR in ./node_modules/container-query-polyfill/cqfill.js 63:36
Module parse failed: Unexpected token (63:36)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   let borderBox;
|   if ("borderBoxSize" in entry) {
>     borderBox = entry.borderBoxSize?.[0] ?? entry.borderBoxSize;
|   } else {
|     const computed = getComputedStyle(entry.target);
 @ ./packages/components/helpers/container-polyfill/h-container-polyfill.js 11:0-34
 @ ./packages/components/helpers/container-polyfill/h-container-polyfill.stories.js
 @ ./packages/components sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(?:\[tj\]|[tj])s)$
 @ ./generated-stories-entry.js
 @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./node_modules/webpack-hot-middleware/client.js?reload=true&quiet=false&noInfo=undefined ./storybook-init-framework-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/common/config.js-generated-config-entry.js ./node_modules/@storybook/addon-docs/dist/esm/frameworks/html/config.js-generated-config-entry.js ./node_modules/@storybook/html/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-actions/dist/esm/preset/addArgs.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-backgrounds/dist/esm/preset/addParameter.js-generated-config-entry.js ./node_modules/@storybook/addon-measure/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-outline/dist/esm/preset/addDecorator.js-generated-config-entry.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js

**Comment by surma** [comment]
Seems like your version of webpack doesn’t support `.?` or `??`. I can’t help you with configuring webpack tho.

**Comment by hog-seruj** [comment]
"webpack": "^5.40.0",

**Comment by hog-seruj** [comment]
const glob = require('glob');
const path = require('path');
const SpriteLoaderPlugin = require('svg-sprite-loader/plugin');
const TerserPlugin = require('terser-webpack-plugin');
const WarningsToErrorsPlugin = require('warnings-to-errors-webpack-plugin');
const options = require('./options');

const mapCssFilenamesToEntries = (pattern, globOptions) =>
  glob.sync(pattern, globOptions).reduce((entries, filename) => {
    const [, name] = filename.match(/([^/]+)\.css$/);
    return {
      ...entries,
      [name]: filename,
    };
  }, {});

const mapJsFilenamesToEntries = ({ pattern, globOptions, filenameIgnore }) =>
  glob.sync(pattern, globOptions).reduce((entries, filename) => {
    const [, name] = filename && filename.match(/([^/]+)\.js$/);
    const nameNormalized = name.endsWith('.es6')
      ? `${name.replace(/.{0,4}$/, '')}.es5`
      : name;
    const entiresNormalized =
      name !== filenameIgnore ? { [nameNormalized]: filename } : {};
    return {
      ...entries,
      ...entiresNormalized,
    };
  }, {});

module.exports = {
  context: options.theme.js,
  entry: {
    app: './init.js',
    ...mapCssFilenamesToEntries(options.cssFiles.components, {
      ignore: options.cssFiles.ignore,
    }),
    ...mapJsFilenamesToEntries({
      pattern: `${options.theme.js}/**/*.js`,
      filenameIgnore: 'init',
    }),
    sprite: glob.sync(path.resolve(__dirname, 'images/svg/**/*.svg')),
  },
  output: {
    path: options.rootPath.dist,
    filename: 'js/[name].js',
  },
  mode: 'production',
  module: {
    rules: [
      {
        test: /\.yml$/,
        use: [
          {
            loader: '@skilld/kaizen-breakpoints/loader',
          },
        ],
      },
      {
        test: /\.css$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: 'css/[name].css',
              sourceMap: process.env.NODE_ENV === 'development',
            },
          },
          {
            loader: 'extract-loader',
            options: {
              sourceMap: process.env.NODE_ENV === 'development',
            },
          },
          {
            loader: 'css-loader',
            options: {
              sourceMap: process.env.NODE_ENV === 'development',
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: process.env.NODE_ENV === 'development',
            },
          },
        ],
      },
      {
        test: /\.svg$/,
        use: {
          loader: 'svg-sprite-loader',
          options: {
            extract: true,
            symbolId: (filePath) =>
              `svg-${path.basename(filePath.slice(0, -4))}`,
            publicPath: 'svg/',
          },
        },
      },
      // Uncomment if you have theme-stored fonts.
      // {
      //   test: /\.(woff|woff2)$/,
      //   loader: 'file-loader',
      //   options: {
      //     outputPath: 'fonts',
      //     publicPath: '../fonts',
      //   },
      // },
    ],
  },
  plugins: [
    new WarningsToErrorsPlugin(),
    new SpriteLoaderPlugin({
      plainSprite: true,
    }),
  ],
  optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
        extractComments: true,
        terserOptions: {
          mangle: {
            reserved: ['Drupal'],
          },
        },
      }),
    ],
  },
};

**Comment by surma** [comment]
Again, I can’t help you with webpack. I don’t know webpack. You need to find out how to enable “nullish coalescing operator” and “optional chaining operator” in webpack. 

I’m gonna close this. Please ask the webpack folks for help :D

**Comment by hog-seruj** [comment]
@surma  Thx for your work. May be will be helpful for other: this is work with Webpack https://github.com/jsxtools/cqfill

**Comment by clamchoda** [comment]
Just use rollup, works fine.
