### ISSUE TITLE
Pseudo elements support

### ISSUE THREAD

**Issue by robertpiosik** [GoogleChromeLabs/container-query-polyfill#14]
Please, add support for pseudo elements 🙏🏻

**Comment by surma** [comment]
Don’t think that’s possible as they are _pseudo_ elements, they don’t have a real DOM handle. As a result, I can’t observe them with `ResizeObserver`.

**Comment by robertpiosik** [comment]
Yeah, that's unfortunate, created #15 to metion it in the readme.
