### ISSUE TITLE
container-name support

### ISSUE THREAD

**Issue by robertpiosik** [GoogleChromeLabs/container-query-polyfill#16]
Looks like not supporting `container-name`.

[CSS_Container_Queries#container-name](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries#container-name)

**Comment by surma** [comment]
It does support named containers. ([Here](https://github.com/GoogleChromeLabs/container-query-polyfill/blob/main/tests/named.html)’s one of the tests)
