### ISSUE TITLE
Infinite loop when parsing HTML document with curly brackets

### ISSUE THREAD

**Issue by kspar** [GoogleChromeLabs/container-query-polyfill#20]
Hey, I'm using the [Super Dark Mode](https://chrome.google.com/webstore/detail/super-dark-mode/nlgphodeccebbcnkgmokeegopgpnjfkc) browser plugin that injects a fake stylesheet link without href into the HTML (see example below). This causes cqfill to parse the main HTML document as CSS. 

And for some reason, if the HTML contains Mustache/Handlebars templating tags in a specific order, cqfill lands in an infinite loop.

Minimal example to reproduce:
```html
<html>

<!-- Added by browser plugin -->
<link type="text/css" id="dark-mode" rel="stylesheet" href="">

<head>
</head>
<body>
abc

<script type="text/x-handlebars">
    {{#foo}}
    {{/foo}} <!-- Infinite loop when looking at first { on this line -->
    {{#foo}}
    {{/foo}}
</script>

<script src="https://unpkg.com/container-query-polyfill/cqfill.iife.min.js"></script>
</body>
</html>
```

So I guess there's two misbehaviors that don't cause issues on their own but result in a big problem together:
* If the HTML contains a stylesheet link tag with no href, then cqfill will attempt to parse the current HTML document as CSS.
* If the string-to-be-parsed contains curly braces (and perhaps other symbols) in a specific way, then cqfill will land in an infinite loop.

**Comment by surma** [comment]
Should be fixed in v0.1.2 :)
