### ISSUE TITLE
Issues with dynamically added styles

### ISSUE THREAD

**Issue by Zachiah** [GoogleChromeLabs/container-query-polyfill#21]
Hi! It seems like the polyfill isn't working on my SPA when new styles are loaded, is this expected? and if so is there a workaround?

**Comment by surma** [comment]
No, that should work. Can you create a small, reproducible test case that shows the problem?

**Comment by Zachiah** [comment]
Will try! thanks for the reply

**Comment by devknoll** [comment]
As Surma mentioned, this is something that should be working. I'm going to close out this issue for now, but I'm happy to reopen it if you can post a repro case.

Thank you!
