### ISSUE TITLE
Exceptions relating to media queries

### ISSUE THREAD

**Issue by thomasheartman** [GoogleChromeLabs/container-query-polyfill#23]
Hi 👋🏼 Super stoked to see a polyfill for this! Thanks for your work 😄 

I wanted to try this out on a Docusaurus page for a custom component, but when loading the polyfill, I get the following two errors:

```
Uncaught DOMException: Element.matches: '@media (min-width: 1440px) ' is not a valid selector cqfill.js:130
```

```
Uncaught (in promise) DOMException: Document.querySelectorAll: '@media (min-width: 1440px) ' is not a valid selector cqfill.js:204
```

I'm not entirely sure what's going on, but it seems to me that `@media[...]` gets picked up as a rule and that it breaks some queries. That said, I may very well be doing something wrong. This happens both in Firefox 96 and in Chrome 97.

Do you have any ideas about what may be going wrong and/or how I can fix it?

Thanks for any input!

**Comment by Nagell** [comment]
Same here. Is there any reason why @media should not be used with container queries?

**Comment by surma** [comment]
Can either of you provide me with a as-small-as-possible stylesheet that triggers this exception? As long a you don’t nest CQs inside MQs, it is _supposed_ to work, but there might be bugs :D

**Comment by thomasheartman** [comment]
I can try if it's relevant, but in my case, I don't even need to use container queries in my styling. Just importing the polyfill causes the errors. 

On closer inspection, my guess is that it's these lines in the docusaurus styles (line 3019--3023) that cause the problem and that it's related to #9. The lines in question are:

```css
@media (min-width: 1440px) {
    .container {
      max-width: var(--ifm-container-width-xl);
    }
}
```

**Comment by Nagell** [comment]
There it is:

`.container {
	margin-left: auto;
	margin-right: auto
}

.container-fluid {
	width: auto;
	max-width: 100%;
	margin-left: 1.5rem;
	margin-right: 1.5rem
}

@media (min-width: 768px) {
	.container-fluid {
		margin-left: 2rem;
		margin-right: 2rem
	}
}

.container {
	width: 100%
}

@media (min-width: 640px) {
	.container {
		max-width: 640px
	}
}

@media (min-width: 768px) {
	.container {
		max-width: 768px
	}
}

@media (min-width: 1024px) {
	.container {
		max-width: 1024px
	}
}

@media (min-width: 1280px) {
	.container {
		max-width: 1280px
	}
}

@media (min-width: 1536px) {
	.container {
		max-width: 1536px
	}
}

@media (min-width: 1920px) {
	.container {
		max-width: 1920px
	}
}`

Most probably it is this one: 

`@media (min-width: 768px) {
	.container {
		max-width: 768px
	}
}`

but some of these rules are autogenerated from tailwind, so I cannot be sure.

**Comment by RodrigoTomeES** [comment]
I have the same issue, I am using the last version of the polyfill, v.0.1.2 and I am getting the error -> Document.querySelectorAll: '@media (min-width: 375px) ' is not a valid selector

![imagen](https://user-images.githubusercontent.com/13077343/166210487-4f38d98f-ba0b-449d-8135-a1e751fe9c6b.png)

![imagen](https://user-images.githubusercontent.com/13077343/166211153-5e171e11-b41b-4c45-9988-f07aebe5d6a1.png)

I am using React v17.0.2 and NextJS 12.1.0.

I add the import in useEffect inside the _app file

**Comment by devknoll** [comment]
This issue should be fixed by the latest version of the polyfill (currently in alpha). Let me know if you run into any further problems and I'd be happy to reopen the issue.

Thank you!
