### ISSUE TITLE
Failed to execute 'matches' on 'Element': '@media only screen and (max-width : 480px)

### ISSUE THREAD

**Issue by Enebz** [GoogleChromeLabs/container-query-polyfill#31]
![image](https://user-images.githubusercontent.com/46542339/160937466-b7184fd6-939d-4b37-a871-5353bced0244.png)
Theese are some errors that I am getting after trying to use **Tailwind CSS** in my **React** project. I am using the tailwindcss-container-query plugin [https://github.com/dgknca/tailwindcss-container-query](url).

**Comment by th0th** [comment]
Did you manage to resolve this @Enebz ?

**Comment by Enebz** [comment]
Yes @th0th!
You have to use this as a local package though: https://github.com/lilles/container-query-polyfill/tree/skip-at-rules-20220402
It has been sent as a PR here: https://github.com/GoogleChromeLabs/container-query-polyfill/pull/33
