### ISSUE TITLE
Requesting container height on container-type: inline-size

### ISSUE THREAD

**Issue by KolyaKorruptis** [GoogleChromeLabs/container-query-polyfill#35]
Using this polyfill I can request a container's height on a `container-type: inline-size`: 

```
.teaser {
  container-type: inline-size;
}

@container (min-height: 530px) {
 ...
}
```

[Live-Example](https://kolya.schwarzsilber.de/tomato-editor/#eyJoIjoiPGRpdiBjbGFzcz1cInRlYXNlclwiPlxuICDTGl9faW1hZ2VcIj48L2RpdsYnaDLRJmhsXCI+SGVhZGxpbmU8L2gyxipw0k9udHJvXCI+TG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZWxpdC4gQWxpcXVhbSB0aW5jaWR1bnQsIG5pc2kgcXVpcyBtYXR0aXMgaW1wZXJkacRMZXJvcyBwdXJ1c8xLbGlndWxhLMY1yxhtZXR1c+cAlnZlbMYKLjwvcD5cbugBATxzY3JpcHQgc3JjPVwiaHR0cHM6Ly91bnBrZy5jb20vY29udGFpbmVyLXF1ZXJ5LXBvbHlmaWxsL2NxxAcuaWlmZS5taW4uanPlAVfGTz5cbiIsImMiOiJib2R5IHvkAT9tYXJnaW46IDA7xA5wYWRkaW5nOiAxcmVtxRJib3gtc2l6xRVib3JkZXItYm94O1xufVxuXG4u5gFzxkvFK2hhZG93OiAxcHjFBDNweCAwICMzMzPHTsVCcmFkaXVzOsQe13fqAOF0eXBlOiBpbuQB9eQAimXPfOcCPuYAg3dpZHRoOiAxMDAlxUdhc3BlY3QtcmF0aW86IDEvMcUWYmFja2dyb3VuZDogdXJsKOgBYHBpY+QBi3Bob3Rvcy8zMDDEBCkgbm8tcmVwZWF0IGNlbnRlcsgHLyBjb3ZlcvIAkOQCf+YAkGRpc3BsYXk6IG5vbukAuUDpAN0gKG1pbi1oZWlnaHQ6IDUzMHB4KcY51E3LT2Jsb2Nr5QDMfcVVIiwiaiI6IsUJ5AEkIjp7Ind3IjoiMTA1N3B4Iiwid+QDlzkyNMUNacQbNTAwxg3GGjNweCJ9fQ==)

My understanding is that this request on the block-axis should only be possible if `container-type: size;`. 
Is the current behavior according to spec?

**Comment by KolyaKorruptis** [comment]
This is the part of the spec I am referring to: 
W3C Draft Level-3 on **container-type**: https://drafts.csswg.org/css-contain-3/#container-type

> size
: Establishes a query container for container size queries on both the inline and block axis.
> inline-size: 
Establishes a query container for container size queries on the container’s own inline axis.

Chrome's native implementation does not follow this height-request on a `container-type: inline-size`, but the polyfill does.
Not that I'm complaining, I just want to write CSS that works for native implementations in future. And this is at least a gotcha.

**Comment by devknoll** [comment]
Thank you for your issue!

The newest version of the polyfill (currently in alpha) more closely follows the spec, and does not allow you to query e.g. `block-size` on an `inline-size` container.
