### ISSUE TITLE
Uncaught (in promise) Error: Advanced beyond the end

### ISSUE THREAD

**Issue by martinszeltins** [GoogleChromeLabs/container-query-polyfill#36]
I wanted to try out this polyfill but I am getting this error:

````
Uncaught (in promise) Error: (http://127.0.0.1:43842/index.html): Advanced beyond the end
    at S (cqfill.iife.min.js:1:4128)
    at k (cqfill.iife.min.js:1:3637)
    at z (cqfill.iife.min.js:1:3712)
    at B (cqfill.iife.min.js:1:3845)
    at Q (cqfill.iife.min.js:1:3961)
    at C (cqfill.iife.min.js:1:2655)
    at t (cqfill.iife.min.js:2:484)
````

I only have 2 simple files at the moment. Here is my `index.html`:

````
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>CSS</title>
        <script src="cqfill.iife.min.js"></script>
        <link rel="stylesheet" href="style.css">
    </head>

    <body>
        <div class="card">
            <div class="card__title">
                Card title
            </div>

            <div class="card__body">
                Card body
            </div>
        </div>
    </body>
</html>
````

And here is my `style.css`:

````
html, body {
    background: #22272e;
}

body {
    min-height: 100vh;
    color: #adbac7;
}

.card {
    background: #2d333b;
    border-radius: 10px;
}

.card__title,
.card__body {
    padding: 10px 8px;
}

.card__title {
    background: #353d46;
    border-top-right-radius: inherit;
    border-top-left-radius: inherit;
}
````

**Comment by devknoll** [comment]
This issue should be fixed by the newest version of the polyfill (currently in alpha). Please give it a try and let me know if you run into any more problems.

Thank you!

**Comment by martinszeltins** [comment]
> This issue should be fixed by the newest version of the polyfill (currently in alpha). Please give it a try and let me know if you run into any more problems.
> 
> Thank you!

Thank you @devknoll for picking this project up and continuing development after @surma left. Will give the latest version a try.

**Comment by e10a** [comment]
In my case the parser did not like that I had the following in one of my imported css files:
```@import url("https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;600&family=Inter:wght@400;500;600;700&display=swap");```
