### ISSUE TITLE
What am I doing wrong? 

### ISSUE THREAD

**Issue by blackfalcon** [GoogleChromeLabs/container-query-polyfill#5]
I have the following code

```html
<style>
  .box {
    background-color: orange;
    height: 100px;
  }

  @container (min-width: 400px) {
    .box {
      background-color: green;
    }
  }
</style>

<div class="box"></div>
```

In the browser I see 

<img width="1107" alt="Screen Shot 2021-11-25 at 2 13 14 PM" src="https://user-images.githubusercontent.com/181089/143503956-e99177f3-d34c-4848-8078-7e4de85403b6.png">

I am not seeing the color turn to green?

**Comment by surma** [comment]
@jakob-metro is correct. You have defined a container query, but not a container :) Closing this.
