### ISSUE TITLE
":where() pseudo class not supported" in firefox version that should support it.

### ISSUE THREAD

**Issue by DanielCordell** [GoogleChromeLabs/container-query-polyfill#64]
I am currently using firefox 106, which has support for there `:where()` pseudo-class.

However, if I attempt to run the query demo, I get the following in the console:

![image](https://user-images.githubusercontent.com/16806427/197566095-c993e4f9-27ec-4c0f-8ab6-a8173da685f8.png)

Also contained in the screenshot is proof that `where` is supported. I've also tested it manually by adding a simple `:where(div)` and it's picked up correctly. I am using the polyfill via the CDN URL provided, not using npm. Is there another step I need to take, or is there an issue with firefox currently?

**Comment by gkatsev** [comment]
Looks like it's because the check in the code is `CSS.supports('selector(:where())')` which is returning `false` but adding in `div` to the `:where(div)` makes it return true and as far as I can tell makes it work as expected.

**Comment by gkatsev** [comment]
Submitted a PR for that https://github.com/GoogleChromeLabs/container-query-polyfill/pull/65

**Comment by DanielCordell** [comment]
> Submitted a PR for that #65

Wow, quick stuff, many thanks!
