### ISSUE TITLE
Firefox 106 😢

### ISSUE THREAD

**Issue by jakob-e** [GoogleChromeLabs/container-query-polyfill#68]
I've not had time to dig into this - but it looks like Firefox 106 has "Houston" problems 😔

**Comment by gkatsev** [comment]
Is the issue that it's logging the `:where` not supported in the console? If so, this is fixed in 1.0.2.

**Comment by jakob-e** [comment]
I can see the warning - but I’m not sure if seeing means something was “broken” (skipped)

This example was working as expected in 105 - but stopped working in 106

https://codepen.io/jakob-e/pen/QWrzQrZ

**Comment by gkatsev** [comment]
I can see the warning about `:where` support in the console. Seems to work if I force 1.0.2 https://codepen.io/gkatsev/pen/VwdPOPP

**Comment by jakob-e** [comment]
This made my day - thank you so much 🤩🙏🏻

_Version 1.0.2 link - in case someone needs it_ 
https://cdn.jsdelivr.net/npm/container-query-polyfill@1.0.2/dist/container-query-polyfill.modern.js

**Comment by devknoll** [comment]
Closing, as it seems like it's fixed by 1.0.2.
