### ISSUE TITLE
Polyfill not wotking in latest firefox (107.0.1)

### ISSUE THREAD

**Issue by BennyAlex** [GoogleChromeLabs/container-query-polyfill#73]
Hello,
 
When i visit the demo page (https://codesandbox.io/s/smoosh-glitter-m2ub4w?file=/index.html) on firefox, the page does not behave the same as on chrome.
So I think the polyfill is not working at all?

Thanks for any help.

**Comment by gkatsev** [comment]
that page is linking to a quite older version of the polyfill. If you change it to use 1.0.2, it should work. https://cdn.jsdelivr.net/npm/container-query-polyfill@1.0.2/dist/container-query-polyfill.modern.js

**Comment by gkatsev** [comment]
Also, for reference, Firefox 109 will be shipping container queries 🎉

**Comment by lilles** [comment]
This is most likely the same as issue #64.
